services:
  shiftsync_db:
    image: postgres:16-alpine
    container_name: shiftsync_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shiftsync_user
      POSTGRES_PASSWORD: shiftsync_password
      POSTGRES_DB: shiftsync_db
    ports:
      - "5432:5432"

  shiftsync_pgadmin:
    image: dpage/pgadmin4:9.4
    container_name: shiftsync_db
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - shiftsync_db